apiVersion: v1
kind: Service
metadata:
  name: petri-apiserver
  namespace: default
spec:
  selector:
    app: petri-apiserver
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
